<?php

declare(strict_types=1);

namespace Respect\Relational\Database;

use InvalidArgumentException;

final class Schema
{
    public static function pkAuto(string $driver): string
    {
        return match ($driver) {
            'sqlite' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
            'mysql' => 'INT AUTO_INCREMENT PRIMARY KEY',
            'pgsql' => 'INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            default => throw new InvalidArgumentException('Unsupported driver: ' . $driver),
        };
    }

    public static function dateTime(string $driver): string
    {
        return match ($driver) {
            'sqlite', 'mysql' => 'DATETIME',
            'pgsql' => 'TIMESTAMP',
            default => throw new InvalidArgumentException('Unsupported driver: ' . $driver),
        };
    }
}
