name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
      - uses: ramsey/composer-install@v3
      - run: composer phpunit

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
      - uses: ramsey/composer-install@v3
      - run: composer phpstan
